server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://sharath.c1cusmki8e6m.us-east-1.rds.amazonaws.com:3306/sharath
    username: admin
    password: Sharath198
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect